"use client";

import { Flame, Scale, Sparkles, Target } from "lucide-react";

import { AiCoachCard } from "@/components/insights/ai-coach-card";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ProgressSummary } from "@/lib/progress/service";

export interface InsightsData {
  today: {
    calories: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    fiberG: number;
    logCount: number;
  };
  streak: number;
  week: { daysLogged: number; avgCalories: number | null; avgProteinG: number | null };
  goal: Pick<
    NonNullable<ProgressSummary["goal"]>,
    "calorie_target" | "protein_target_g" | "carb_target_g" | "fat_target_g"
  > | null;
  adherence: ProgressSummary["adherence"];
  weight: {
    latestKg: number | null;
    weeklyTrendKg: number | null;
    changeKg: number | null;
  };
}

/** Deterministic observations — computed from data, never generated by an LLM. */
function buildObservations(d: InsightsData): string[] {
  const out: string[] = [];

  if (d.goal && d.week.avgCalories != null) {
    const delta = d.week.avgCalories - d.goal.calorie_target;
    const pct = Math.round((Math.abs(delta) / d.goal.calorie_target) * 100);
    if (pct <= 5) {
      out.push(
        `Your 7-day average (${d.week.avgCalories} kcal) is within 5% of your ${d.goal.calorie_target} kcal target — consistency is the win here.`
      );
    } else if (delta > 0) {
      out.push(
        `You're averaging ${delta} kcal/day above target this week. One swap — e.g. a smaller portion of the highest-calorie item — usually closes a gap like this.`
      );
    } else {
      out.push(
        `You're averaging ${Math.abs(delta)} kcal/day below target. If weight loss is stalling or you feel low-energy, consider raising the target on the Goals page.`
      );
    }
  }

  if (d.goal && d.week.avgProteinG != null) {
    const ratio = d.week.avgProteinG / d.goal.protein_target_g;
    if (ratio < 0.75) {
      out.push(
        `Protein is at ${Math.round(ratio * 100)}% of your ${d.goal.protein_target_g} g target. Adding a protein anchor (dal, paneer, eggs, curd, chicken) to your biggest meal is the easiest fix.`
      );
    } else if (ratio >= 1) {
      out.push(
        `Protein target hit this week (avg ${d.week.avgProteinG} g vs ${d.goal.protein_target_g} g). Great for satiety and muscle retention.`
      );
    }
  }

  if (d.adherence && d.adherence.daysLogged >= 3) {
    out.push(
      `${d.adherence.pct}% of the days you logged (${d.adherence.daysWithinCalorieTarget}/${d.adherence.daysLogged}) landed inside your calorie band.`
    );
  }

  if (d.weight.weeklyTrendKg != null && Math.abs(d.weight.weeklyTrendKg) >= 0.05) {
    const dir = d.weight.weeklyTrendKg > 0 ? "up" : "down";
    out.push(
      `Weight is trending ${dir} ~${Math.abs(d.weight.weeklyTrendKg).toFixed(2)} kg/week (latest ${d.weight.latestKg?.toFixed(1)} kg). Sustainable range is roughly 0.25–1 kg/week.`
    );
  }

  if (d.streak >= 3) {
    out.push(`You're on a ${d.streak}-day logging streak. Streaks beat perfection — keep the chain going.`);
  }

  if (d.today.logCount === 0) {
    out.push("Today has no entries yet. Logging within an hour of eating keeps recall accurate.");
  }

  if (d.goal && d.today.logCount > 0) {
    const remaining = d.goal.calorie_target - d.today.calories;
    if (remaining > 200) {
      out.push(
        `${remaining} kcal remaining today with ${d.goal.protein_target_g - d.today.proteinG} g protein still to hit — a protein-led dinner fits the budget.`
      );
    } else if (remaining < 0) {
      out.push(
        `You're ${Math.abs(remaining)} kcal over target today. Not a problem on its own — tomorrow's totals matter more than one day.`
      );
    }
  }

  return out.slice(0, 5);
}

export function InsightsView({ data }: { data: InsightsData }) {
  const observations = buildObservations(data);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Insights</h1>
        <p className="text-muted-foreground text-sm">
          Deterministic observations from your own data — computed, not hallucinated.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <Card>
          <CardContent className="flex items-center gap-3 pt-6">
            <Flame className="text-primary size-8 shrink-0" aria-hidden />
            <div>
              <p className="text-2xl font-semibold tabular-nums">{data.streak}</p>
              <p className="text-muted-foreground text-xs">day logging streak</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 pt-6">
            <Target className="text-primary size-8 shrink-0" aria-hidden />
            <div>
              <p className="text-2xl font-semibold tabular-nums">
                {data.adherence?.pct != null ? `${data.adherence.pct}%` : "—"}
              </p>
              <p className="text-muted-foreground text-xs">days within calorie band</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 pt-6">
            <Sparkles className="text-primary size-8 shrink-0" aria-hidden />
            <div>
              <p className="text-2xl font-semibold tabular-nums">
                {data.week.avgCalories ?? "—"}
              </p>
              <p className="text-muted-foreground text-xs">avg kcal (7 days)</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 pt-6">
            <Scale className="text-primary size-8 shrink-0" aria-hidden />
            <div>
              <p className="text-2xl font-semibold tabular-nums">
                {data.weight.latestKg != null ? data.weight.latestKg.toFixed(1) : "—"}
              </p>
              <p className="text-muted-foreground text-xs">kg latest weight</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">What your data says</CardTitle>
          <CardDescription>
            Rule-based analysis of your last 28 days — computed from your own data.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {observations.length === 0 ? (
            <p className="text-muted-foreground text-sm">
              Log a few days of food and weight, and personalized observations will appear here.
            </p>
          ) : (
            <ul className="space-y-3">
              {observations.map((o, i) => (
                <li key={i} className="flex gap-3 text-sm">
                  <span className="bg-primary/10 text-primary mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full text-xs font-semibold">
                    {i + 1}
                  </span>
                  <p className="leading-relaxed">{o}</p>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>

      <AiCoachCard />

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Today so far</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-3 text-center sm:grid-cols-5">
            {[
              { label: "kcal", value: data.today.calories, target: data.goal?.calorie_target },
              { label: "Protein g", value: data.today.proteinG, target: data.goal?.protein_target_g },
              { label: "Carbs g", value: data.today.carbsG, target: data.goal?.carb_target_g },
              { label: "Fat g", value: data.today.fatG, target: data.goal?.fat_target_g },
              { label: "Fiber g", value: data.today.fiberG, target: null }
            ].map((t) => (
              <div key={t.label} className="bg-muted/60 rounded-xl p-3">
                <p className="text-lg font-semibold tabular-nums">{t.value}</p>
                <p className="text-muted-foreground text-xs">
                  {t.label}
                  {t.target != null ? ` / ${t.target}` : ""}
                </p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
